### PR TITLE
Implement a vanilla deck creator

### PR DESCRIPTION
**Pull request by gcoter**
For now our objective is to play Magic without abilities, so we only need vanilla cards.

Implement these issues:
- #19
- #18

### CODE REVIEW

**Comment by gcoter** [comment]
I am not sure about how to handle colors. Should a deck contain only one color? Two colors?

Also, I see that a card can have several colors (see `color_identity` in the CSV files)

**Comment by MaximeBastion** [comment]
> I am not sure about how to handle colors. Should a deck contain only one color? Two colors?
> 
> Also, I see that a card can have several colors (see `color_identity` in the CSV files)

Good question. I'd say ideally the deck creator takes a list of colors as arg and builds a deck that features these colors, although this complexifies things a bit since this the deck will need to be roughly equally split between those colors.
Also, we could say that a card is eligible for a deck if all its colors are among the decks's colors.
Btw the color identity of a card is different from its colors: "Color identity is a [property](https://mtg.fandom.com/wiki/Property) of cards in the [Commander format](https://mtg.fandom.com/wiki/Commander_(format)) and its variants (e.g. [Brawl](https://mtg.fandom.com/wiki/Brawl)). It expands the concept of a card's [color](https://mtg.fandom.com/wiki/Color) beyond the [mana cost](https://mtg.fandom.com/wiki/Mana_cost) to all elements of the card. Color identity forms one of the the key deck construction rules for Commander formats as players are not allowed to use any card whose color identity is not included in the color identity of their [commander](https://mtg.fandom.com/wiki/Commander_(designation))."
For vanilla creatures it's the same but could be different for other cards.

It's also ok to just have monocolored decks for now and worry about that later.

**Comment by MaximeBastion** [comment]
I'd say the most common number of colors featured in a deck are 1 and 2

**Comment by gcoter** [comment]
Ok thanks :slightly_smiling_face: I think for now I will create monocolored decks and filter cards with only the chosen color, just for simplicity. Then in the future, we could add a second color.

**Comment by gcoter** [comment]
> Btw the color identity of a card is different from its colors

Does it mean we should deduce the color from the mana cost to be more generic?

**Comment by gcoter** [comment]
I'm going to merge this PR because I want to use it to test the combats in #35

**Pull request merged**
