### PR TITLE
Combat simulator

### PR DESCRIPTION
**Pull request by gcoter**
Implement these issues:
- #32

### CODE REVIEW

**Comment by gcoter** [comment]
I added a script to simulate one combat, it can be run like this: `PYTHONPATH=. python3 magic_the_gathering/simulate_combat.py`

**Comment by gcoter** [comment]
I simulated a combat with these cards:
- Player 0 has:
  - [Coral Eel (2/1)](https://scryfall.com/card/9ed/S3/coral-eel) (uuid=e5fd9c5e-84d6-4965-83a1-2d77ea4838ca)
  - [Seagraf Skaab (1/3)](https://scryfall.com/card/soi/84/seagraf-skaab) (uuid=31042091-62c8-42b2-9774-b10cbd595704)
- Player 1 has:
  - [Mons's Goblin Raiders (1/1)](https://scryfall.com/card/s00/32/monss-goblin-raiders) (uuid=79e4b7f8-b530-4d66-a718-66648047940c)
  - [Hill Giant (3/3)](https://scryfall.com/card/10e/212/hill-giant) (uuid=30e6db99-ad2b-4573-83c5-a5088a84d12a)

Here are the logs:
```
INFO:CombatBeginningPhase:===== Combat: Beginning Phase =====
INFO:CombatDeclareAttackersPhase:===== Combat: Declare Attackers Phase =====
Press enter to continue...
Press enter to continue...
INFO:CombatDeclareAttackersPhase:Declared attackers: {1: ['31042091-62c8-42b2-9774-b10cbd595704', 'e5fd9c5e-84d6-4965-83a1-2d77ea4838ca']}
INFO:CombatDeclareBlockersPhase:===== Combat: Declare Blockers Phase =====
Press enter to continue...
Press enter to continue...
INFO:CombatDeclareBlockersPhase:Declared blockers: {1: {'31042091-62c8-42b2-9774-b10cbd595704': ['79e4b7f8-b530-4d66-a718-66648047940c', '30e6db99-ad2b-4573-83c5-a5088a84d12a'], 'e5fd9c5e-84d6-4965-83a1-2d77ea4838ca': []}}
INFO:CombatDamagePhase:===== Combat: Damage Phase =====
Press enter to continue...
INFO:DealDamageAction:Card(uuid=31042091-62c8-42b2-9774-b10cbd595704, name=Seagraf Skaab, color_identity=['U'], type=Creature — Zombie, mana_cost={'W': 0, 'U': 1, 'B': 0, 'R': 0, 'G': 0, 'any': 1}, power=1, toughness=3, state=CardState(is_tapped=True, owner_player_id=0, started_turn_controlled_by_player_id=0, damage_marked=4)) receives 4 damage from blockers
INFO:DealDamageAction:Card(uuid=79e4b7f8-b530-4d66-a718-66648047940c, name=Mons's Goblin Raiders, color_identity=['R'], type=Creature — Goblin, mana_cost={'W': 0, 'U': 0, 'B': 0, 'R': 1, 'G': 0, 'any': 0}, power=1, toughness=1, state=CardState(is_tapped=True, owner_player_id=1, started_turn_controlled_by_player_id=1, damage_marked=1)) receives 1 damage from Card(uuid=31042091-62c8-42b2-9774-b10cbd595704, name=Seagraf Skaab, color_identity=['U'], type=Creature — Zombie, mana_cost={'W': 0, 'U': 1, 'B': 0, 'R': 0, 'G': 0, 'any': 1}, power=1, toughness=3, state=CardState(is_tapped=True, owner_player_id=0, started_turn_controlled_by_player_id=0, damage_marked=4))
INFO:DealDamageAction:Card(uuid=30e6db99-ad2b-4573-83c5-a5088a84d12a, name=Hill Giant, color_identity=['R'], type=Creature — Giant, mana_cost={'W': 0, 'U': 0, 'B': 0, 'R': 1, 'G': 0, 'any': 3}, power=3, toughness=3, state=CardState(is_tapped=True, owner_player_id=1, started_turn_controlled_by_player_id=1, damage_marked=0)) receives 0 damage from Card(uuid=31042091-62c8-42b2-9774-b10cbd595704, name=Seagraf Skaab, color_identity=['U'], type=Creature — Zombie, mana_cost={'W': 0, 'U': 1, 'B': 0, 'R': 0, 'G': 0, 'any': 1}, power=1, toughness=3, state=CardState(is_tapped=True, owner_player_id=0, started_turn_controlled_by_player_id=0, damage_marked=4))
INFO:DealDamageAction:Player 1 receives 2 damage from Card(uuid=e5fd9c5e-84d6-4965-83a1-2d77ea4838ca, name=Coral Eel, color_identity=['U'], type=Creature — Fish, mana_cost={'W': 0, 'U': 1, 'B': 0, 'R': 0, 'G': 0, 'any': 1}, power=2, toughness=1, state=CardState(is_tapped=True, owner_player_id=0, started_turn_controlled_by_player_id=0, damage_marked=0))
Press enter to continue...
INFO:MoveToGraveyardAction:Move card 31042091-62c8-42b2-9774-b10cbd595704 of Player 0 to graveyard
Press enter to continue...
INFO:MoveToGraveyardAction:Move card 79e4b7f8-b530-4d66-a718-66648047940c of Player 1 to graveyard
INFO:CombatEndPhase:===== Combat: End Phase =====
```

In English, here is what happens:
1) Player 0 declares two attackers (Coral Eel and Seagraf Skaab) against Player 1
2) Player 1 declares two blockers (Mons's Goblin Raiders and Hill Giant) against Seagraf Skaab but none against Coral Eel
3) Attacker Seagraf Skaab receives 4 damages from the blockers (which is the sum of power 1 from Mons's Goblin Raiders and power 3 from Hill Giant)
4) Blocker Mons's Goblin Raiders receives one damage from Seagraf Skaab (which has power 1)
5) Hill Giant receives 0 damage from Seagraf Skaab (since its power 1 was used on Mons's Goblin Raiders)
6) Player 1 receives 2 damage from attacker Coral Eel (which has power 2) since it was not blocked
7) Attacker Seagraf Skaab is moved to the graveyard since the 4 marked damages exceed its toughness of 3
8) Blocker Mons's Goblin Raiders is moved to the graveyard since the 1 marked damage equals its toughness of 1

@MaximeBastion Is it all correct according to the rules of Magic? :slightly_smiling_face:

**Comment by gcoter** [comment]
I tried to simulate 100 combats with 7 attackers and 7 potential blockers, the average time to simulate one combat is 0.007 seconds :slightly_smiling_face:

**Comment by MaximeBastion** [comment]
Noice
- (don't know if it happened or not) The attacking player must have the opportunity to order blockers for sub-battles where there are multiple blockers in front of 1 attacker
- I'd say Hill Giant should not receive 0 damage but not have the action at all, or at least we'll need a check for damage dealt is 0 somewhere
A random example where it could matter is when you have a lifelink creature like [Mesa Unicorn](https://scryfall.com/card/jmp/122/mesa-unicorn) and smth that pays you off when you gain life lie [Ajani's Pridemate](https://scryfall.com/card/war/4/ajanis-pridemate), we don't want to trigger it

**Comment by gcoter** [comment]
> The attacking player must have the opportunity to order blockers for sub-battles where there are multiple blockers in front of 1 attacker

I forgot to mention it but here I made the assumption that the blockers are already ordered, ordering by the attacker is a missing feature for now (I created this issue to track this #39)

> I'd say Hill Giant should not receive 0 damage but not have the action at all, or at least we'll need a check for damage dealt is 0 somewhere

Oh I see, I didn't think it would matter, I will fix it, thanks 🙂

**Comment by gcoter** [comment]
> I'd say Hill Giant should not receive 0 damage but not have the action at all, or at least we'll need a check for damage dealt is 0 somewhere

Finally, I created this issue to track it as for now I am confused about the best way to implement it: #40

**Comment by gcoter** [comment]
I will merge this PR now, issues were opened for things which are left to implement

**Pull request merged**
