### PR TITLE
Make it possible to save all the data related to a game

### PR DESCRIPTION
**Pull request by gcoter**
Implement #25

### CODE REVIEW

**Comment by gcoter** [comment]
First quick implementation of writing the `GameState` as json, it returns something like this:
```
{
    "game_mode": {
        "name": "Default Game Mode",
        "initial_life_points": 20,
        "initial_hand_size": 7
    },
    "players": [
        {
            "life_points": 20,
            "mana_pool": {
                "W": 0,
                "U": 0,
                "B": 0,
                "R": 0,
                "G": 0
            },
            "is_alive": true
        },
        {
            "life_points": 20,
            "mana_pool": {
                "W": 0,
                "U": 0,
                "B": 0,
                "R": 0,
                "G": 0
            },
            "is_alive": true
        }
    ],
    "current_turn_counter": 0,
    "current_player_index": 0,
    "current_player_has_played_a_land_this_turn": false,
    "zones": {
        "HAND": [
            {
                "uuid": "eb8037db-d164-4d7d-bfe2-33bf10c5b69b",
                "scryfall_uuid": "0ab27f51-230c-469d-9b8a-a21b9d0fccf5",
                "name": "Kami of Old Stone",
                "color_identity": [
                    "W"
                ],
                "type": "Creature \u2014 Spirit",
                "text": "",
                "mana_cost_dict": {
                    "W": 1,
                    "U": 0,
                    "B": 0,
                    "R": 0,
                    "G": 0,
                    "any": 3
                },
                "power": 1.0,
                "toughness": 7.0,
                "state": null
            },
            {
                "uuid": "aa6acb67-d454-4cac-a266-4fc7c7ae6d74",
                "scryfall_uuid": "e070ea4a-c417-405f-b788-78fb7ca2eaa5",
                "name": "Fresh Volunteers",
                "color_identity": [
                    "W"
                ],
                "type": "Creature \u2014 Human Rebel",
                "text": "",
                "mana_cost_dict": {
                    "W": 1,
                    "U": 0,
                    "B": 0,
                    "R": 0,
                    "G": 0,
                    "any": 1
                },
                "power": 2.0,
                "toughness": 2.0,
                "state": null
            },
            {
                "uuid": "4c7e9fc6-7564-4fa9-a0bf-dde68f09715b",
                "scryfall_uuid": "00293ce4-3475-4064-8510-9e8c02faf3bf",
                "name": "Plains",
                "color_identity": [
                    "W"
                ],
                "type": "Basic Land \u2014 Plains",
                "text": "({T}: Add {W}.)",
                "mana_cost_dict": null,
                "power": "",
                "toughness": "",
                "state": null
            },
            {
                "uuid": "0e84d091-3b18-4d24-9071-7fd150cf26af",
                "scryfall_uuid": "00293ce4-3475-4064-8510-9e8c02faf3bf",
                "name": "Plains",
                "color_identity": [
                    "W"
                ],
                "type": "Basic Land \u2014 Plains",
                "text": "({T}: Add {W}.)",
                "mana_cost_dict": null,
                "power": "",
                "toughness": "",
                "state": null
            },
            {
                "uuid": "2790c172-9fe4-4ceb-9eab-e4481208732c",
                "scryfall_uuid": "00293ce4-3475-4064-8510-9e8c02faf3bf",
                "name": "Plains",
                "color_identity": [
                    "W"
                ],
                "type": "Basic Land \u2014 Plains",
                "text": "({T}: Add {W}.)",
                "mana_cost_dict": null,
                "power": "",
                "toughness": "",
                "state": null
            },
            {
                "uuid": "551a7619-2e0d-4429-8d8e-622950d2e257",
                "scryfall_uuid": "89fb4bf8-51b6-44a8-92ac-e5aec4e4f2bc",
                "name": "Devoted Hero",
                "color_identity": [
                    "W"
                ],
                "type": "Creature \u2014 Elf Soldier",
                "text": "",
                "mana_cost_dict": {
                    "W": 1,
                    "U": 0,
                    "B": 0,
                    "R": 0,
                    "G": 0,
                    "any": 0
                },
                "power": 1.0,
                "toughness": 2.0,
                "state": null
            },
            {
                "uuid": "638455ab-8ce3-4429-a015-90f88e369e67",
                "scryfall_uuid": "00293ce4-3475-4064-8510-9e8c02faf3bf",
                "name": "Plains",
                "color_identity": [
                    "W"
                ],
                "type": "Basic Land \u2014 Plains",
                "text": "({T}: Add {W}.)",
                "mana_cost_dict": null,
                "power": "",
                "toughness": "",
                "state": null
            },
            {
                "uuid": "adb27f5f-45f5-4ddf-ba14-891c1347136e",
                "scryfall_uuid": "f2c60e63-0b86-4100-a932-bb9e9b197610",
                "name": "Colossodon Yearling",
                "color_identity": [
                    "G"
                ],
                "type": "Creature \u2014 Beast",
                "text": "",
                "mana_cost_dict": {
                    "W": 0,
                    "U": 0,
                    "B": 0,
                    "R": 0,
                    "G": 1,
                    "any": 2
                },
                "power": 2.0,
                "toughness": 4.0,
                "state": null
            },
            {
                "uuid": "20a5110b-5606-4614-9af4-34bc08e519d6",
                "scryfall_uuid": "05381dc1-50e1-4ac4-8f35-46d0b2d0b42d",
                "name": "Trained Armodon",
                "color_identity": [
                    "G"
                ],
                "type": "Creature \u2014 Elephant",
                "text": "",
                "mana_cost_dict": {
                    "W": 0,
                    "U": 0,
                    "B": 0,
                    "R": 0,
                    "G": 2,
                    "any": 1
                },
                "power": 3.0,
                "toughness": 3.0,
                "state": null
            },
            {
                "uuid": "848acae6-defc-4ff6-884d-cdefd0669634",
                "scryfall_uuid": "c37ae6b5-225a-410e-ab22-13e923bdfb65",
                "name": "Spined Karok",
                "color_identity": [
                    "G"
                ],
                "type": "Creature \u2014 Crocodile",
                "text": "",
                "mana_cost_dict": {
                    "W": 0,
                    "U": 0,
                    "B": 0,
                    "R": 0,
                    "G": 1,
                    "any": 2
                },
                "power": 2.0,
                "toughness": 4.0,
                "state": null
            },
            {
                "uuid": "b7a0106f-6b76-442d-8b2e-ea36b72d8865",
                "scryfall_uuid": "0031d026-9e9a-46f6-8204-1acfee8b8809",
                "name": "Forest",
                "color_identity": [
                    "G"
                ],
                "type": "Basic Land \u2014 Forest",
                "text": "({T}: Add {G}.)",
                "mana_cost_dict": null,
                "power": "",
                "toughness": "",
                "state": null
            },
            {
                "uuid": "51f69731-1f09-4a15-b1e7-0004eb7cd5a1",
                "scryfall_uuid": "4a2e5279-f28c-4a78-9f8a-16c9f72f8d38",
                "name": "Alpha Tyrranax",
                "color_identity": [
                    "G"
                ],
                "type": "Creature \u2014 Dinosaur Beast",
                "text": "",
                "mana_cost_dict": {
                    "W": 0,
                    "U": 0,
                    "B": 0,
                    "R": 0,
                    "G": 2,
                    "any": 4
                },
                "power": 6.0,
                "toughness": 5.0,
                "state": null
            },
            {
                "uuid": "e9b19582-18bb-4c27-b62d-7a33c90dabba",
                "scryfall_uuid": "0031d026-9e9a-46f6-8204-1acfee8b8809",
                "name": "Forest",
                "color_identity": [
                    "G"
                ],
                "type": "Basic Land \u2014 Forest",
                "text": "({T}: Add {G}.)",
                "mana_cost_dict": null,
                "power": "",
                "toughness": "",
                "state": null
            },
            {
                "uuid": "4af28caf-2d18-4c33-a0b5-ae48e640f347",
                "scryfall_uuid": "662dc886-ce6b-4db1-a806-cc0d4fc504f6",
                "name": "Balduvian Bears",
                "color_identity": [
                    "G"
                ],
                "type": "Creature \u2014 Bear",
                "text": "",
                "mana_cost_dict": {
                    "W": 0,
                    "U": 0,
                    "B": 0,
                    "R": 0,
                    "G": 1,
                    "any": 1
                },
                "power": 2.0,
                "toughness": 2.0,
                "state": null
            }
        ],
        "LIBRARY": [<all cards in decks>],
        "BOARD": [],
        "GRAVEYARD": [],
        "EXILE": [],
        "STACK": []
    },
    "current_player_attackers": {},
    "other_players_blockers": {},
    "action_history": [
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 0
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 0
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 0
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 0
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 0
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 0
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 0
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 1
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 1
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 1
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 1
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 1
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 1
            }
        },
        {
            "action_type": "DrawAction",
            "action_attributes": {
                "owner": "game",
                "player_index": 1
            }
        }
    ]
}
```

I hesitate to keep the libraries because they are big and not known by the player (although we could assume that a player is aware of the general composition of his deck without knowing the order of the cards)

**Comment by gcoter** [comment]
I fixed several things and I made it possible to record the files in a folder like this:
```bash
PYTHONPATH=. LOG_DIRECTORY_PATH=logs/ python magic_the_gathering/run_one_game.py
```

It takes 2 to 3 seconds to run one game, writing takes a lot of time. I am wondering whether using a DB would be more efficient

**Comment by gcoter** [comment]
I managed to reduce the time per game to 1 second. The idea is to save one big file (instead of multiple small ones) and use the pickle format (instead of JSON)

**Review by MaximeBastion — APPROVED** [review]
LGTM

**Pull request merged**
